name: Update

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore Cache node dependencies
        uses: actions/cache@v3
        id: cache-npm
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install NPM dependencies if cache miss
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - run: npm run build
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'build'
          destination-github-username: 'thelarapush'
          destination-repository-name: 'Larapush-Docs'
          user-email: larapushcom@gmail.com
          target-branch: 'main'
          target-directory: ''
